### ISSUE TITLE
Missing tests for the API fetching section

### ISSUE THREAD

**Issue by kjleitz** [learn-co-curriculum/react-container-components-lab#11]
There are no tests for the NYT movie reviews API, despite a [section for it in the README](https://github.com/learn-co-curriculum/react-container-components-lab#the-new-york-times-api) and some pre-existing code related to it in `LatestMovieReviewsContainer.js`. All tests pass without ever touching `fetch` or the API itself.

**Comment by FreeBreadsticks** [comment]
I noticed the same thing - I was a little confused by it at first!

**Comment by dkStephanos** [comment]
Still unresolved!!

**Comment by maxwellbenton** [comment]
Thank you for providing this feedback.

We have updated the materials and included fetch tests to make sure calls are being made to the NYT API, and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
