### ISSUE TITLE
No browser output

### ISSUE THREAD

**Issue by dkStephanos** [learn-co-curriculum/react-container-components-lab#14]
Aside from the fact that this lab doesn't actually use the API or fetch calls it refers to, it renders nothing in the browser. It would be nice if the API section was tested in such a way that you actually see data in the browser. As of right now, you just get a bunch of tests to pass, and nothing functions or renders... hardly a strong, realistic example.

**Comment by maxwellbenton** [comment]
Thank you for providing this feedback.

We have updated the materials and to make sure this lab will correctly render in browser when all tests have passed, and included fetch tests to make sure calls are being made to the NYT API, and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
