### ISSUE TITLE
Solution contains error

### ISSUE THREAD

**Issue by AspenJames** [learn-co-curriculum/react-container-components-lab#15]
File: https://github.com/learn-co-curriculum/react-container-components-lab/blob/solution/src/components/SearchableMovieReviewsContainer.js

Issue: missing closing tag for state: 

```
state = {
    searchTerm: '',
    reviews: []

  handleSearchInputChange = event => this.setState({ searchTerm: event.target.value });

  handleSubmit = event => {
    event.preventDefault();

    fetch(BASE_URL.concat(this.state.searchTerm))
      .then(res => res.json())
      .then(res => this.setState({ reviews: res.results }));
}
```

#Staff

**Comment by maxwellbenton** [comment]
Hey @AspenJames,

Thanks for catching this and providing feedback. I've updated the solution and fixed this.
