### ISSUE TITLE
Restrictive Tests

### ISSUE THREAD

**Issue by micahshute** [learn-co-curriculum/react-container-components-lab#17]
The way the tests are written they do not allow for any nesting of presentational components as described in previous lessons. For example, creating an individual `MovieReview` component, or a `Search` component for the search form causes test failures due to using `shallow` in the tests. 

__I recommend__ using `mount` instead of `shallow` specifically for the last test in `MovieReviews_test.js` (should render all the reviews), and the second to last test in `SearchableMovieReviewsContainer_test.js` (should fetch data from the New York Times API on form submission). Note that `mount` has to be imported (same import statement as `shallow`) in `MovieReviews_test.js` for this to work, but it is already imported into `SearchableMovieReviewsContainer_test.js` and just requires a `wrapper` redefinition using `mount` in the second to last test). 

Making these changes allows further breakdown of presentational components if students want to practice using that pattern.

**Comment by RylanBauermeister** [comment]
Just want to jump in and second this issue.  Was trying to code by example, and this one stumped me for a solid 30 minutes.  Not ideal.

**Comment by maxwellbenton** [comment]
Hey @micahshute and @RylanBauermeister ,

Thank you for providing this feedback. I've updated the tests in this lab to use `mount` which should resolve this issue for future students. The tests should also still use `shallow` if functional components are used (which, from testing, do seem to work with nested components, as long as they are all functional).

We apologize for any frustration this lab may have caused, but we appreciate you taking the time to provide feedback and help us improve our curriculum for future students!

Thank you!
