### ISSUE TITLE
NYT API Update

### ISSUE THREAD

**Issue by karsonkalt** [learn-co-curriculum/react-container-components-lab#28]
NYT API documentation and links have changed. Please update readme.

**Comment by ihollander** [comment]
Hi @karsonkalt , we updated the readme recently to reflect changes to the API in this commit: https://github.com/learn-co-curriculum/react-container-components-lab/commit/4ab14b4fbe0d3ab3094b8a8218f41038a00cb14d

This changes may not have been reflected in Canvas for all students, depending on what time you started working on this course.
