### ISSUE TITLE
Errors lack clarity for resolution

### ISSUE THREAD

**Issue by drewkeat** [learn-co-curriculum/react-container-components-lab#29]
### Canvas Link

https://learning.flatironschool.com/courses/1883/assignments/125688?module_item_id=259638

### Concern

I'm not sure what the issue is.   TDD errors imply that reviews should update when state is changed in container components.  This works fine in the browser...

<LatestMovieReviewsContainer />
    ✓ should have state
    ✓ should have a state property "reviews"
    ✓ should have top-level element with class "latest-movie-reviews"
    ✓ should fetch data from the New York Times API
    1) should render reviews after reviews state updated

  <MovieReviews />
    ✓ should be a stateless functional component
    ✓ should have a top-level component with class "review-list"
    2) should render all the reviews

  <SearchableMovieReviewsContainer />
    ✓ should have state
    ✓ should have the state properties "reviews" and "searchTerm"
    ✓ should fetch data from the New York Times API on form submission
    3) should render reviews after reviews state updated

  9 passing (78ms)
  3 failing

  1) <LatestMovieReviewsContainer />
       should render reviews after reviews state updated:

      AssertionError: expected 0 to equal 3
      + expected - actual

      -0
      +3
      
      at Context.<anonymous> (test/LatestMovieReviewsContainer_test.js:52:47)
      at processImmediate (node:internal/timers:464:21)

  2) <MovieReviews />
       should render all the reviews:

      AssertionError: expected 0 to equal 3
      + expected - actual

      -0
      +3
      
      at Context.<anonymous> (test/MovieReviews_test.js:45:47)
      at processImmediate (node:internal/timers:464:21)

  3) <SearchableMovieReviewsContainer />
       should render reviews after reviews state updated:

      AssertionError: expected 0 to equal 3
      + expected - actual

      -0
      +3
      
      at Context.<anonymous> (test/SearchableMovieReviewsContainer_test.js:61:47)
      at processImmediate (node:internal/timers:464:21)

### Additional Context

I'm sorry that I can't provide much further context.  The application seems to function correctly in my browser (updating reviews when state changes in either container component).  However, the errors that I'm receiving indicate that this isn't the case.

Feel free to check my work [Forked Repo](https://github.com/drewkeat/react-container-components-lab)

### Suggested Changes

N/A

**Comment by ihollander** [comment]
Hi @drewkeat - it looks like your `MovieReviews` component is missing the `review` class that the tests need as specified in the readme:

> You are free to lay out each review as you like using the data that the API returns, but make sure that the component outputs a top-level element with the class review-list and that each review is wrapped by an element with class review.

You can always check the test code itself to try and understand why certain tests aren't passing, or use the [solution branch](https://github.com/learn-co-curriculum/react-container-components-lab/tree/solution) to compare your solution.

Since this isn't a curriculum issue, I'm closing this report.

**Comment by drewkeat** [comment]
Thank you, Ian I apologize for my confusion.

Drew Keat
