### ISSUE TITLE
whatwg-fetch vs node-fetch

### ISSUE THREAD

**Issue by Enoch2k2** [learn-co-curriculum/react-container-components-lab#6]
In the lesson it states that whatwg-fetch is a good api library for using fetch. However the testing doesn't work with fetch. When using ```import fetch from 'whatwg-fetch'``` and also the alternative ```import 'whatwg-fetch'``` , fetch comes up undefined. As to where the ```import fetch from 'whatwg-fetch'``` comes up with a different error(something about a default).

With ```node-fetch```, all you have to do is ```const fetch = require('node-fetch')``` and your done. You can use fetch in the file.

Documentation for node-fetch: https://www.npmjs.com/package/node-fetch

Documentation why whatwg-fetch doesn't work here: https://github.com/github/fetch/issues/329

![screen shot 2016-12-13 at 8 26 33 pm](https://cloud.githubusercontent.com/assets/16408135/21167508/8454dca6-c172-11e6-85e0-0e621398735b.png)

I wanted to bring this up because I spent over half my day trying to make whatwg-fetch work haha. There may of been a way or something i hadn't been able to do to get it working. I wanted to bring up ```node-fetch``` because it's easy to use.

**Comment by nothingisfunny** [comment]
I had the same problem, learn instructor told me to use `const { fetch } = require('whatwg-fetch'` to import that library. That fixed the issue.

**Comment by Lukeghenco** [comment]
@Enoch2k2 and @nothingisfunny this will be fixed with the move to webpack. Thanks for raising the issue.
